name: Deploy docs

on:
  push:
    paths: ['src/**', 'astro.config.mjs', '.github/workflows/deploy-docs.yml', 'bun.lockb']
    branches:
      - main
  release:
    types: [created]

env:
  SITE_ORIGIN: https://${{github.repository_owner}}.github.io
  BASE_PATH: '/${{ github.event.repository.name }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install, build, and upload the site
        uses: withastro/action@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
